version: '3.8'

services:
  local_db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: assignment
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306
    volumes:
      - local_db_data:/var/lib/mysql
    networks:
      - assignment_network
volumes:
  local_db_data:
networks:
  assignment_network: